server:
  port: 8080

spring:
  application:
    name: fastadmin
  profiles:
    active: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    content-type: text/html
    mode: LEGACYHTML5
logging:
  level:
    root: debug
  file: log
  path: ./log
